In [2]:
import numpy as np
import pandas as pd

C:\Users\singh\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [5]:
patients = pd.read_csv('SWD.csv')

In [6]:
patients

,Date,Date_YMD,Status,Total,Hospitalized,Recovered,Deceased,Mask,Sanitizer,Oxygen,...,RJ,SK,TN,TG,TR,UP,UT,WB,UN,State
0,14-Mar-20,14-03-2020,Confirmed,81,12,120,0,10,60,48,...,3,0,1,1,0,12,0,0,0,Maharashtra
1,14-Mar-20,14-03-2020,Recovered,9,25,5,2,20,1,38,...,1,0,0,0,0,4,0,0,0,Maharashtra
2,14-Mar-20,14-03-2020,Deceased,2,85,10,4,30,0,0,...,0,0,0,0,0,0,0,0,0,Maharashtra
3,15-Mar-20,15-03-2020,Confirmed,27,89,15,0,40,41,57,...,1,0,0,2,0,1,0,0,0,Maharashtra
4,15-Mar-20,15-03-2020,Recovered,4,10,5,21,50,4,55,...,2,0,0,1,0,0,0,0,0,Maharashtra
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1786,30-Oct-21,30-10-2021,Recovered,14672,0,14,10,371,2,2,...,1,3,1172,191,8,9,6,880,0,Lakshdweep
1787,30-Oct-21,30-10-2021,Deceased,445,22,1,0,4,0,0,...,0,0,14,1,0,0,0,13,0,Lakshdweep
1788,31-Oct-21,31-10-2021,Confirmed,12907,50,20,1,212,8,5,...,2,21,1009,121,12,6,5,914,0,Lakshdweep
1789,31-Oct-21,31-10-2021,Recovered,13152,1,23,9,236,9,3,...,2,8,1183,183,2,6,9,913,0,Lakshdweep
1790,31-Oct-21,31-10-2021,Deceased,251,23,0,0,1,0,0,...,0,1,19,1,0,0,0,15,0,Lakshdweep

In [9]:
patients['Status'].value_counts()

Status
Confirmed    597
Recovered    597
Deceased     597
Name: count, dtype: int64

In [16]:
total = patients.shape[0]
active = patients[patients['Status'] == 'Confirmed'].shape[0]
recovered = patients[patients['Status'] == 'Recovered'].shape[0]
deceased = patients[patients['Status'] == 'Deceased'].shape[0]

In [19]:
deceased = patients[patients['Status'] == 'Deceased'].shape[0]
deceased

597